classDiagram
direction TB

    namespace UI {
        class App {
            +Run() void
        }

        class GameLayout {
            -string _eventMsg
            -MessageType _eventMsgType
            -GameController _controller
            +GameLayout(GameController)
            +Render(IPage page) IPage?
        }

        class IPage {
            <<interface>>
            +Index() IPage?
        }

        class MainMenuPage {
            -GameController _controller
            +Index() IPage?
        }

        class GameInitPage {
            -GameController _controller
            +Index() IPage?
        }

        class ShipPlacementPage {
            -GameController _controller
            -ShipPlacementResponseDto _state
            +Index() IPage?
        }

        class GameBoardPage {
            -GameController _controller
            -AttackResponseDto _state
            +Index() IPage?
        }

        class TransitionPage {
            -GameController _controller
            -AttackResponseDto _state
            +Index() IPage?
        }

        class GameOverPage {
            -GameController _controller
            -AttackResponseDto _state
            +Index() IPage?
        }
    }

    namespace Controllers {
        class GameController {
            -IGameService _gameService
            +event MessageDelegate? OnMessage
            +GameController()
            +LoadGame() void
            +StartShipPlacementPhase(StartPlacementPhaseDto) ShipPlacementResponseDto
            +EditShipPlacement(EditShipPlacementDto) ShipPlacementResponseDto
            +MakeAttack(AttackDto) AttackResponseDto
        }
    }

    namespace DTOs {
        class StartPlacementPhaseDto {
            +string PlayerOneName
            +string PlayerTwoName
            +int BoardSize = 10
        }

        class EditShipPlacementDto {
            +Ship? CurrentShip
            +ConsoleKey KeyEvent
            +Coordinate IndexPlayerCursor
        }

        class ShipPlacementResponseDto {
            +IBoard Board
            +List~IShip~ Ships
            +IPlayer CurrentPlayer
            +IShip? SelectedShip
            +Coordinate IndexPlayerCursor
            +bool IsValidPlacement
            +bool IsPlacementPhaseFinished
        }

        class AttackDto {
            +Coordinate Target
        }

        class AttackResponseDto {
            +IBoard PlayerBoard
            +IBoard OpponentBoard
            +IPlayer CurrentPlayer
            +Coordinate LastAttack
            +AttackResult LastResult
            +bool IsGameOver
            +IPlayer? Winner
        }
    }

    namespace Services {
        class IGameService {
            <<interface>>
            +IPlayer CurrentPlayer
            +StartShipPlacementPhase(StartPlacementPhaseDto) ShipPlacementResponseDto
            +EditShipPlacement(EditShipPlacementDto) ShipPlacementResponseDto
            +MakeAttack(AttackDto) AttackResponseDto
        }

        class GameService {
            -List~IPlayer~ _players
            -Dictionary _playerBoard
            -Dictionary _playerShips
            -int _indexCurrentPlayer
            -IShip? _selectedShip
            -Coordinate _indexPlayerCursor
            -List~PlacementState~ _undoStack
            -List~PlacementState~ _redoStack
            -MessageDelegate _messageProvider
            +GameService(MessageDelegate)
            +StartShipPlacementPhase(StartPlacementPhaseDto) ShipPlacementResponseDto
            +EditShipPlacement(EditShipPlacementDto) ShipPlacementResponseDto
            +MakeAttack(AttackDto) AttackResponseDto
        }
    }

    namespace Models {
        class IShip {
            <<interface>>
            +ShipType ShipType
            +Orientation Orientation
            +List~ICell~? Placement
        }

        class Ship {
            +Ship(ShipType type, Orientation orientation)
        }

        class IPlayer {
            <<interface>>
            +string Name
        }

        class Player {
            +Player(string name)
        }

        class IBoard {
            <<interface>>
            +ICell[,] Cell
            +int Size
        }

        class Board {
            +Board(int size)
        }

        class ICell {
            <<interface>>
            +IShip? Ship
            +Coordinate Coordinate
            +AttackResult? ReceivedAttackResult
        }

        class Cell {
            +Cell(Coordinate coordinate)
        }
    }

    namespace Types {
        class MessageDelegate {
            <<delegate>>
            Invoke(string msg, MessageType type) void
        }

        class MessageType {
            <<enum>>
            Info
            Debug
            Error
        }

        class Coordinate {
            <<struct>>
            +HorizontalLabel X
            +VerticalLabel Y
        }

        class ShipType {
            <<enum>>
            Destroyer = 2
            Submarine = 3
            Cruiser = 3
            Battleship = 4
            Carrier = 5
        }

        class VerticalLabel {
            <<enum>>
            A B C D E F G H I J
        }

        class HorizontalLabel {
            <<enum>>
            _1 _2 _3 _4 _5 _6 _7 _8 _9 _10
        }

        class AttackResult {
            <<enum>>
            Hit
            Miss
            Sunk
        }

        class Orientation {
            <<enum>>
            Horizontal
            Vertical
        }
    }

    %% Inheritance
    IPage       <|.. MainMenuPage      : implements
    IPage       <|.. GameInitPage      : implements
    IPage       <|.. ShipPlacementPage : implements
    IPage       <|.. GameBoardPage     : implements
    IPage       <|.. TransitionPage    : implements
    IPage       <|.. GameOverPage      : implements
    IShip       <|.. Ship              : implements
    IPlayer     <|.. Player            : implements
    IBoard      <|.. Board             : implements
    ICell       <|.. Cell              : implements
    IGameService <|.. GameService      : implements

    %% Composition / dependencies
    App              --> GameLayout
    GameLayout       --> GameController
    GameLayout       o-- IPage

    MainMenuPage     --> GameController
    GameInitPage     --> GameController
    ShipPlacementPage --> GameController
    GameBoardPage    --> GameController
    TransitionPage   --> GameController
    GameOverPage     --> GameController

    GameController   --> IGameService
    GameController   ..> MessageDelegate : fires

    GameService      ..> IPlayer  : manages
    GameService      ..> IBoard   : manages
    GameService      ..> IShip    : manages

    IBoard           o-- ICell
    IShip            o-- ICell
