classDiagram
direction RL
    namespace UI {
        class App {
            
        }
    }

    namespace Controllers {
        class GameController {
            -IGameService _gameService
            +event Action<string>? OnMessage;
            +event Action? OnGameEnded;
            
            GameController(): void
        }
    }

    namespace DTOs {
        class StartGameDto {
            +string PlayerOneName
            +string PlayerTwoName
            +int BoardSize = 10
        }

        class AttackResponseDto {
            +IPlayer CurrentPlayer
            +Board 
        }
    }

    namespace Services {
        class IGameService {
            -List~IPlayer~ _players
            -List~IBoard~ _boards
            -Dictionary<.IPlayer IBoard> _playerBoard
            -Dictionary ~IPlayer#44; List~IShip~~ _shipsOnBoard
            +IPlayer CurrentPlayer 

            +StartGame(StartGameDto) void
        }
    
        class GameService {
            GameService()
            -IsHit(ICell cell)
        }
    }

    namespace Model {
        class IShip {
            +ShipType Type
            +int remainingParts
            +List~Cell~ Placement
            +Orietation Orientation = Orientation.Horizontal
        }

        class Ship {
            Ship(ShipType type)
        }

        class IPlayer {
            +string Name
            +IBoard Board
        }

        class Player {
            Player(string name)
        }

        class IBoard {
            +ICell[,] Cell
            +int Size
        }

        class Board {
            Board(int size)
        }


        class ICell {
            +IShip? Ship
            +Coordinate Coordinate
            AttackResult? ReceivedAttackResult
        }

        class Cell {
            Cell(Coordinate coordinate)
        }
    }

    namespace Types {
        class Coordinate {
            <<struct>>
            X: int
            Y: int
        }

        class ShipType {
            <<enum>>
            Destroyer = 2
            Submarine = 3
            Cruiser = 3 
            Battleship = 4
            Carrier = 5
        }

        class VerticalLabel {
            <<enum>>
            A
            B
            C
            ...
            H
        }

        class HorizontalLabel {
            <<enum>>
            1
            2
            3
            ...
            8
        }

        class AttackResult {
            <<enum>>
            Hit
            Miss
            Sunk
        }

        class Orietation {
            <<enum>>
            Horizontal
            Vertical
        }
    }

    IShip <|.. Ship : Implements
    IPlayer <|.. Player : Implements
    IBoard <|.. Board: Implements
    ICell <|.. Cell: Implements


    
    

    